version: "3.2"
services:
 redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
 mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "33306:3306"
 webapp:
    image: yurush/blog-project
    depends_on:
      - "redis"
      - "mysql"
    ports:
      - "9090:8080"